package com.myfitnessbuddy.entities;
import java.util.List;

import jakarta.persistence.*;

@Entity
@Table(name = "exercises")
public class Exercise {
    // id best for pulling exercises from db
    // this is manually generated by the db when a new exercise is created
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String exerciseName;
    private List<String> muscleGroupsWorked;
    private int sets;
    private int reps;
    private int length;
    private String date;

    public Exercise(String exerciseName, List<String> muscleGroupsWorked, int sets, int reps, int length, String date) {
        this.exerciseName = exerciseName;
        this.muscleGroupsWorked = muscleGroupsWorked;
        this.sets = sets;
        this.reps = reps;
        this.length = length;
        this.date = date;
    }

    // TODO: add getters / setters
}

