package com.myfitnessbuddy.entities;
import jakarta.persistence.*;
// import java.util.ArrayList;
// import java.util.List;

@Entity
@Table(name = "users")
public class User {
    // id best for pulling users from db
    // this is manually generated by the db when a new user is created
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private int age;
    private double weight; // sepcify height units
    private double height; // specify weight units
    private String fitnessGoals;
    private String gender;
    // @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    // private List<FoodItem> historicalFood;
    // @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    // private List<Exercise> historicalExercises;

    public User() {}

    public User(String name, int age, double weight, double height, String fitnessGoals, String gender) {
        this.name = name;
        this.age = age;
        this.weight = weight;
        this.height = height;
        this.fitnessGoals = fitnessGoals;
        this.gender = gender;
        // this.historicalFood = new ArrayList<>();
        // this.historicalExercises = new ArrayList<>();
    }

    public void logDailyCalories(FoodItem foodItem) {
        //Stores user calorie intake for a specific day.
    }

    public void logWorkout(Exercise exercise) {
        //Logs a completed workout session.
    }

    // not sure why these return a new data structure but keeping here for legacy purposes

    // public List<FoodItem> getHistoricalCalories(String startDate, String endDate) {
    //     //Retrieves user calorie intake history for a given time range.
    //     return new ArrayList<>();
    // }

    // public List<Exercise> getHistoricalWorkouts(String startDate, String endDate) {
    //     //Retrieves user workout history for a given time range.
    //     return new ArrayList<>();
    // }

    // GETTERS

    public Long getId() { return id; }
    public String getName() { return name; }
    public int getAge() { return age; }
    public double getWeight() { return weight; }
    public double getHeight() { return height; }
    public String getFitnessGoals() { return fitnessGoals; }
    public String getGender() { return gender; }
    // public List<FoodItem> getHistoricalFood() { return historicalFood; }
    // public List<Exercise> getHistoricalExercises() { return historicalExercises; }

    // SETTERS

    public void setId(Long id) { this.id = id; }
    public void setName(String name) { this.name = name; }
    public void setAge(int age) { this.age = age; }
    public void setWeight(double weight) { this.weight = weight; }
    public void setHeight(double height) { this.height = height; }
    public void setFitnessGoals(String fitnessGoals) { this.fitnessGoals = fitnessGoals; }
    public void setGender(String gender) { this.gender = gender; }
    // public void setHistoricalFood(List<FoodItem> historicalFood) { this.historicalFood = historicalFood; }
    // public void setHistoricalExercises(List<Exercise> historicalExercises) { this.historicalExercises = historicalExercises; }
}